### PR TITLE
pushing more gui changes, can now look at current point and the amoun…

### PR DESCRIPTION
**Pull request by dacabdi**
…t of neighbors it has

### CODE REVIEW

**Comment by dacabdi** [comment]
@chababster , can you fix the conflicts? thanks!

**Comment by chababster** [comment]
Fixed conflicts, it was just where I’m messing with auto progression

Thank you,
Andrew Chabab
University of Florida CISE
President, UF Student InfoSec Team
(772) 626 – 9123
[sit]

**Comment by dacabdi** [comment]
@chababster it is still showing that the branch has conflicts to resolve...

**Comment by chababster** [comment]
Yea just saw that, working on fixing it now

Thank you,
Andrew Chabab
University of Florida CISE
President, UF Student InfoSec Team
(772) 626 – 9123
[sit]

**Comment by chababster** [comment]
Alright this should be fixed now, apologies for that

Thank you,
Andrew Chabab
University of Florida CISE
President, UF Student InfoSec Team
(772) 626 – 9123
[sit]

**Pull request merged**
